# Generated by Django 4.2.1 on 2023-05-18 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.CharField(max_length=100)),
                ('excerpt', models.TextField(max_length=200)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
