# Generated by Django 4.2.1 on 2023-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.CharField(default='https://latrilha.com.br/wp-content/uploads/2023/04/53.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
