# Generated by Django 4.2.1 on 2023-05-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='post_date',
        ),
    ]
